### ISSUE TITLE
Only check for software limits when a joint can actuate

### ISSUE THREAD

**Issue by Ishadijcks** [project-march/hardware-interface#48]
When the hardware_interface gets launched, there is a check to see if we are within safetylimits [here](https://github.com/project-march/hardware-interface/blob/develop/march_hardware_interface/src/march_hardware_interface.cpp#L95).

However sometimes while debugging the encoder, this check crashes because the encoder will read a 0, which is almost always out of its limits.

@martijnvandermarel @TimBuckers @Bart-van-Ingen, I'd like each of your opinions on this issue. Should it be possible to allow continuation when *outside the limits while actuationmode is off*?

**Comment by martijnvandermarel** [comment]
I can't see anything going wrong (aka physically break stuff) when you can't actuate, so that would speak for allowing this. However, when the encoders are configured wrong, the main question is: Why would you actually want to continue? I can imagine you want to test for example the temperatures of the joint or do stuff with the PDB or something. Therefore, I am in favor of allowing continuation when actuationmode is off (preferably still give a warning, though).

**Comment by Ishadijcks** [comment]
When the encoder returns 0, you want to move it and see if the value changes. This is the most common usecase I believe

**Comment by JitskedeVries** [comment]
Do you mean move the joint by hand and see if the value changes? I think that must be allowed.

Actuating the motor to see if the value changes, must not be allowed. You could obviously break something if we don't know what the encoder value is and we don't know to what value we can move.

**Comment by JitskedeVries** [comment]
I agree with you both. The encoder can be outside its limits when launching, especially when you want to test something else. But when you are going to actuate, the encoder value must be inside it limits. Thus the error can be thrown later in the process (just before actuating).

**Comment by Ishadijcks** [comment]
This would be based off the `allowActuation` property which cannot change at runtime.
